In [35]:
import pandas as pd
import numpy as np

books = pd.read_csv("../data/raw/books.csv")

books.head()

,Unnamed: 0,bookId,title,author,series,description,genres,awards,characters,places,...,publish_date,num_pages,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
0,0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,Harry Potter #6,The war against Voldemort is not going well; e...,"Art,Biography,Business,Children's,Christian,Cl...",Locus Award Nominee for Best Young Adult Novel...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","Hogwarts School of Witchcraft and Wizardry,Eng...",...,September 16th 2006,652.0,2553909.0,41470.0,4.57,13147.0,29020.0,174312.0,608825.0,1728605.0
1,1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré",Harry Potter #5,There is a door at the end of a silent corrido...,"Art,Biography,Business,Children's,Christian,Cl...",Bram Stoker Award for Works for Young Readers ...,"Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...","Hogwarts School of Witchcraft and Wizardry,Lon...",...,September 2004,870.0,2631427.0,44793.0,4.50,16236.0,41738.0,231438.0,665628.0,1676387.0
2,2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré",Harry Potter #1,Harry Potter's life is miserable. His parents ...,"Art,Biography,Business,Children's,Christian,Cl...",Mythopoeic Fantasy Award for Children's Litera...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","London, England,Hogwarts School of Witchcraft ...",...,November 1st 2003,309.0,7434783.0,117823.0,4.48,126344.0,147184.0,627803.0,1694206.0,4839246.0
3,3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,Harry Potter #2,The Dursleys were so mean and hideous that sum...,"Art,Biography,Business,Children's,Christian,Cl...",Mythopoeic Fantasy Award for Children's Litera...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","Hogwarts School of Witchcraft and Wizardry,Hog...",...,November 1st 2003,352.0,2878196.0,55839.0,4.43,15623.0,55060.0,315917.0,787181.0,1704415.0
4,4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré",Harry Potter #3,"For twelve long years, the dread fortress of A...","Art,Biography,Business,Children's,Christian,Cl...",Bram Stoker Award for Best Work for Young Read...,"Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...","Hogwarts School of Witchcraft and Wizardry,Lon...",...,May 1st 2004,435.0,2972519.0,58483.0,4.57,14124.0,29105.0,214151.0,701765.0,2013374.0

In [36]:
print("Shape:", books.shape)
print()

print("Columns:")
print(books.columns)

Shape: (20068, 24)

Columns:
Index(['Unnamed: 0', 'bookId', 'title', 'author', 'series', 'description',
       'genres', 'awards', 'characters', 'places', 'isbn', 'isbn13',
       'language', 'first_publish_date', 'publish_date', 'num_pages',
       'num_ratings', 'num_reviews', 'avg_rating', 'rated_1', 'rated_2',
       'rated_3', 'rated_4', 'rated_5'],
      dtype='object')

In [37]:
books.isnull().sum().sort_values(ascending=False)

awards                16939
places                16028
series                15789
characters            15289
first_publish_date     5477
rated_5                3430
rated_3                3430
rated_2                3430
rated_4                3430
rated_1                3430
language               2779
description            2687
isbn                   2537
num_pages              1640
publish_date           1046
isbn13                  858
author                  561
avg_rating              559
num_ratings             559
title                   559
num_reviews             559
genres                  256
bookId                    0
Unnamed: 0                0
dtype: int64

In [38]:
books.duplicated().sum()

np.int64(0)

In [39]:
books["genres"].head()

0    Art,Biography,Business,Children's,Christian,Cl...
1    Art,Biography,Business,Children's,Christian,Cl...
2    Art,Biography,Business,Children's,Christian,Cl...
3    Art,Biography,Business,Children's,Christian,Cl...
4    Art,Biography,Business,Children's,Christian,Cl...
Name: genres, dtype: object

In [40]:
math_keywords = [
    "mathematics",
    "calculus",
    "algebra",
    "statistics",
    "probability",
    "analysis",
    "topology",
    "graph theory",
    "optimization",
    "machine learning"
]

books["genres"] = books["genres"].fillna("").str.lower()

math_books = books[
    books["genres"].apply(
        lambda x: any(k in x for k in math_keywords)
    )
]

In [41]:
print(books.columns.tolist())
books.head()
books.shape

['Unnamed: 0', 'bookId', 'title', 'author', 'series', 'description', 'genres', 'awards', 'characters', 'places', 'isbn', 'isbn13', 'language', 'first_publish_date', 'publish_date', 'num_pages', 'num_ratings', 'num_reviews', 'avg_rating', 'rated_1', 'rated_2', 'rated_3', 'rated_4', 'rated_5']

(20068, 24)

Audit Data

In [42]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20068 entries, 0 to 20067
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          20068 non-null  int64
 1   bookId              20068 non-null  int64
 2   title               19509 non-null  object
 3   author              19507 non-null  object
 4   series              4279 non-null   object
 5   description         17381 non-null  object
 6   genres              20068 non-null  object
 7   awards              3129 non-null   object
 8   characters          4779 non-null   object
 9   places              4040 non-null   object
 10  isbn                17531 non-null  object
 11  isbn13              19210 non-null  object
 12  language            17289 non-null  object
 13  first_publish_date  14591 non-null  object
 14  publish_date        19022 non-null  object
 15  num_pages           18428 non-null  float64
 16  num_ratings         19509 non-null  float64
 17  num_reviews         19509 non-null  float64
 18  avg_rating          19509 non-null  float64
 19  rated_1             16638 non-null  float64
 20  rated_2             16638 non-null  float64
 21  rated_3             16638 non-null  float64
 22  rated_4             16638 non-null  float64
 23  rated_5             16638 non-null  float64
dtypes: float64(9), int64(2), object(13)
memory usage: 3.7+ MB

In [43]:
books.isnull().sum().sort_values(ascending=False)

awards                16939
places                16028
series                15789
characters            15289
first_publish_date     5477
rated_5                3430
rated_3                3430
rated_2                3430
rated_4                3430
rated_1                3430
language               2779
description            2687
isbn                   2537
num_pages              1640
publish_date           1046
isbn13                  858
author                  561
avg_rating              559
num_ratings             559
title                   559
num_reviews             559
genres                    0
bookId                    0
Unnamed: 0                0
dtype: int64

In [44]:
books.duplicated().sum()

np.int64(0)

In [45]:
books = books.drop_duplicates()

books = books.dropna(
    subset=[
        "title",
        "description",
        "genres"
    ]
)

books.shape

(17381, 24)

In [46]:
books["genres"].head(10)

0     art,biography,business,children's,christian,cl...
1     art,biography,business,children's,christian,cl...
2     art,biography,business,children's,christian,cl...
3     art,biography,business,children's,christian,cl...
4     art,biography,business,children's,christian,cl...
5     art,biography,business,children's,christian,cl...
7     art,biography,business,children's,christian,cl...
8     art,biography,business,children's,christian,cl...
9     art,biography,business,children's,christian,cl...
10    art,biography,business,children's,christian,cl...
Name: genres, dtype: object

In [47]:
books["genres"].value_counts().head(20)

genres
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult                                                                                                                                                                             3102
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,nonfiction                                                                                                                                                                   117
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fiction                                                                                                                                                                       69
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,history                                                                                                                                                                       53
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,philosophy                                                                                                                                                                    39
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,childrens                                                                                                                                                                     38
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,poetry                                                                                                                                                                        35
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art                                                                                                                                                                           33
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,biography,nonfiction                                                                                                                                                          29
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,music                                                                                                                                                                         28
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,history,nonfiction                                                                                                                                                            24
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,biography                                                                                                                                                                     24
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,business                                                                                                                                                                      23
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fantasy,classics,fiction,adventure,science fiction fantasy,fantasy,epic fantasy,literature,fantasy,high fantasy,young adult,novels                                            23
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,classics                                                                                                                                                                      21
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,classics,fiction,philosophy,spirituality,religion,literature,religion,buddhism,european literature,german literature,novels,historical,historical fiction                     20
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,classics,fiction,historical,historical fiction,literature,literature,american,novels,new york,literature,20th century,classics,classic literature,historical                  19
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,food and drink,cookbooks                                                                                                                                                      19
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fiction,classics,magical realism,literature,novels,fantasy,historical,historical fiction,european literature,spanish literature,literary fiction,cultural,latin american      18
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,plays                                                                                                                                                                         18
Name: count, dtype: int64

In [48]:
books[
    books["genres"]
    .str.contains("math", case=False, na=False)
].head()

,Unnamed: 0,bookId,title,author,series,description,genres,awards,characters,places,...,publish_date,num_pages,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
335,335,335,Lots and Lots of Zebra Stripes,Stephen R. Swinburne,NaN,With a simple text and vivid full-color photog...,"art,biography,business,children's,christian,cl...",NaN,NaN,NaN,...,March 1st 2002,32.0,40.0,8.0,3.83,0.0,3.0,12.0,14.0,11.0
405,405,405,Ratner's Star,Don DeLillo,NaN,"One of DeLillo's first novels,,follows Billy, ...","art,biography,business,children's,christian,cl...",NaN,Billy Twillig,NaN,...,July 17th 1989,448.0,1937.0,181.0,3.47,82.0,267.0,627.0,573.0,388.0
770,770,771,"The Elegant Universe: Superstrings, Hidden Dim...",Brian Greene,NaN,"Brian Greene, one of the world's leading strin...","art,biography,business,children's,christian,cl...",Royal Society Science Book Prize for General P...,NaN,NaN,...,September 2nd 2004,425.0,88906.0,1997.0,4.07,2142.0,3581.0,15056.0,33096.0,35031.0
772,772,773,The ELEGANT UNIVERSE S.S.,Brian Greene,NaN,"Brian Greene, one of the world's leading strin...","art,biography,business,children's,christian,cl...",Royal Society Science Book Prize for General P...,NaN,NaN,...,February 3rd 2000,NaN,88906.0,1997.0,4.07,2142.0,3581.0,15056.0,33096.0,35031.0
1775,1775,1777,Einstein's Heroes: Imagining the World Through...,Robyn Arianrhod,NaN,Imagine you are fluent in a magical language o...,"art,biography,business,children's,christian,cl...",NaN,NaN,NaN,...,July 1st 2006,323.0,97.0,12.0,3.71,0.0,7.0,30.0,44.0,16.0

In [49]:
books[["title", "genres"]].head(10)

,title,genres
0,Harry Potter and the Half-Blood Prince,"art,biography,business,children's,christian,cl..."
1,Harry Potter and the Order of the Phoenix,"art,biography,business,children's,christian,cl..."
2,Harry Potter and the Sorcerer's Stone,"art,biography,business,children's,christian,cl..."
3,Harry Potter and the Chamber of Secrets,"art,biography,business,children's,christian,cl..."
4,Harry Potter and the Prisoner of Azkaban,"art,biography,business,children's,christian,cl..."
5,Harry Potter and the Goblet of Fire,"art,biography,business,children's,christian,cl..."
7,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...","art,biography,business,children's,christian,cl..."
8,"Unauthorized Harry Potter Book Seven News: \""H...","art,biography,business,children's,christian,cl..."
9,Harry Potter Collection,"art,biography,business,children's,christian,cl..."
10,The Hitchhiker's Guide to the Galaxy,"art,biography,business,children's,christian,cl..."

In [50]:
books["genres"].iloc[0]

"art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fantasy,young adult,fiction,fantasy,magic,childrens,adventure,audiobook,childrens,middle grade,classics,science fiction fantasy"

In [51]:
books["genres"].nunique()

9358

In [52]:
books[["title", "genres"]].sample(10)

,title,genres
2946,"The Best of Twain, 8 Vols","art,biography,business,children's,christian,cl..."
2592,LA Guerra De LA Mercadotecnia (Marketing Warfare,"art,biography,business,children's,christian,cl..."
8977,"*planet of the Apes* as American Myth: Race, P...","art,biography,business,children's,christian,cl..."
14305,The Lives of Rocks,"art,biography,business,children's,christian,cl..."
12859,Things Fall Apart,"art,biography,business,children's,christian,cl..."
3892,The Healthy College Cookbook: Quick. Cheap. Easy.,"art,biography,business,children's,christian,cl..."
10684,Carrie,"art,biography,business,children's,christian,cl..."
11590,The Gift of Asher Lev,"art,biography,business,children's,christian,cl..."
18618,A Break with Charity: A Story about the Salem ...,"art,biography,business,children's,christian,cl..."
20030,Artesia Volume 3: Afire - The Third Book Of Dooms,"art,biography,business,children's,christian,cl..."

In [53]:
books["genres"].value_counts().head(10)

genres
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult                         3102
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,nonfiction               117
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fiction                   69
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,history                   53
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,philosophy                39
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,childrens                 38
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,poetry                    35
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art                       33
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,biography,nonfiction      29
art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,music                     28
Name: count, dtype: int64

In [54]:
books["genres"].str.split(",").explode().str.strip().value_counts().head(50)

genres
fiction                42613
classics               39935
fantasy                39541
nonfiction             39475
mystery                37906
history                37138
historical fiction     37080
biography              36754
young adult            36693
thriller               36682
romance                36599
science fiction        36404
science                36298
memoir                 35675
self help              35603
poetry                 35564
psychology             35480
horror                 35466
business               35445
art                    35408
christian              35358
sports                 35349
travel                 35246
comics                 35193
graphic novels         35111
music                  35014
cookbooks              34931
ebooks                 34762
children's             34762
literature              7768
historical              4275
novels                  3496
childrens               3141
cultural                2974
european literature     2054
religion                1797
humor                   1743
philosophy              1730
academic                1663
american                1586
adventure               1579
contemporary            1565
audiobook               1557
autobiography           1379
literary fiction        1373
adult                   1230
school                  1102
british literature      1085
writing                 1080
short stories           1069
Name: count, dtype: int64

In [55]:
books[
    books["genres"]
    .str.contains("algebra", case=False, na=False)
].head()

Empty DataFrame
Columns: [Unnamed: 0, bookId, title, author, series, description, genres, awards, characters, places, isbn, isbn13, language, first_publish_date, publish_date, num_pages, num_ratings, num_reviews, avg_rating, rated_1, rated_2, rated_3, rated_4, rated_5]
Index: []

[0 rows x 24 columns]

In [ ]:
books[
    books["genres"]
    .str.contains("calculus", case=False, na=False)
].head()

,Unnamed: 0,bookId,title,author,series,description,genres,awards,characters,places,...,publish_date,num_pages,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
6664,6664,6639,Calculus Made Easy,Silvanus Phillips Thompson,NaN,has been a classic introduction to the subject...,"art,biography,business,children's,christian,cl...",NaN,NaN,NaN,...,March 22nd 1999,336.0,953.0,82.0,4.20,24.0,37.0,113.0,327.0,452.0
17491,17491,17415,Calculus: Single Variable,"Deborah Hughes-Hallett,Andrew M. Gleason,Willi...",NaN,"Now in its fourth edition, Calculus reflects t...","art,biography,business,children's,christian,cl...",NaN,NaN,NaN,...,November 19th 2004,688.0,50.0,2.0,3.48,7.0,5.0,9.0,15.0,14.0

: