In [55]:
# 1. Load 
import pandas as pd
import joblib

books = pd.read_csv(
    "../data/processed/books_for_ml.csv"
)

books.shape

(14987, 6)

In [ ]:
joblib.dump(
    model,
    "../ml/models/knn_model.pkl"
)

joblib.dump(
    vectorizer,
    "../ml/models/tfidf.pkl"
)

joblib.dump(
    books,
    "../ml/models/books.pkl"
)

joblib.dump(
    title_to_index,
    "../ml/models/title_to_index.pkl"
)

joblib.dump(
    tfidf_matrix,
    "../ml/models/tfidf_matrix.pkl"
)

['../ml/models/tfidf_matrix.pkl']

:

In [14]:
# setelah cleaning selesai
books = books.reset_index(drop=True)

# buat content
books["content"] = (
    books["title"].fillna("") + " " +
    books["author"].fillna("") + " " +
    books["description"].fillna("")
)

# HAPUS mapping lama
del title_to_index

# buat mapping baru
title_to_index = pd.Series(
    data=books.index,
    index=books["title"]
)

In [15]:
#3. content
books["content"] = (
    books["title"].fillna("") + " " +
    books["author"].fillna("") + " " +
    books["description"].fillna("")
)

In [16]:
#4. mapping
# 4. mapping
title_to_index = pd.Series(
    books.index,
    index=books["title"]
)

In [21]:
# 5. tfidf
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

tfidf_matrix = vectorizer.fit_transform(
    books["content"]
)

In [20]:
#6. Model
model = NearestNeighbors(
    metric="cosine",
    algorithm="brute"
)

model.fit(tfidf_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [ ]:
title_to_index["1984"]

np.int64(4184)

In [ ]:
books.iloc[title_to_index["1984"]]["title"]

'1984'

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

tfidf_matrix = tfidf.fit_transform(
    books["content"]
)

print(tfidf_matrix.shape)

(14987, 10000)

In [19]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(
    metric="cosine",
    algorithm="brute",
    n_neighbors=6
)

model.fit(tfidf_matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [23]:
title_to_index = pd.Series(
    books.index,
    index=books["title"]
).drop_duplicates()

In [22]:
def recommend(book_title, top_n=5):

    if book_title not in title_to_index:
        return "Book not found"

    idx = title_to_index[book_title]

    distances, indices = model.kneighbors(
        tfidf_matrix[idx],
        n_neighbors=50
    )
    print("INDEX:", idx)
    print("BOOK:")
    recommendations = books.iloc[
        indices[0][1:]
    ][["title", "author"]]

    recommendations = recommendations.drop_duplicates(
        subset=["title"]
    )

    return recommendations.head(top_n)

In [24]:
books["title"].sample(20)

13493                                      Hapgood: A Play
9058                                             Exzession
10189    Jojo's Bizarre Adventure, Tome 18: Death Thirteen
4736     Birdsongs of the Pacific Northwest [With CD (A...
7867                                      Noel Streatfeild
3737                                Nuestra Proxima Parada
696                                          The Alchemist
4752     Rats Alley: Trench Names of the Western Front ...
6418                                           Blood Sport
2475                     Nineveh and Its Remains, Volume 1
7461     Jesus: God or the Son of God?: A Comparison of...
5679     Winning the Future: A 21st Century Contract Wi...
1756     Mahatma Gandhi and His Myths: Civil Disobedien...
1932                                         Pipes Of Pan.
3947                                  The Heart of a Woman
10508    The Secret Science Project That Almost Ate the...
9376                                      Princess in Love
14318         Father to Son: Life Lessons on Raising a Boy
4439                                         Broken Flower
2837                            E. M. Forster: A Biography
Name: title, dtype: object

In [ ]:
books["title"].sample(20)

8366     Eat Right 4 Your Type: The Individualized Diet...
3912     For Esme—With Love and Squalor, and Other Stories
7384                                     Italian Folktales
13704                 Mass Media Research: An Introduction
2232                                        Flip-Flop Girl
6108                Anne of Green Gables / Anne of Avonlea
6599                     The Old Man Who Read Love Stories
1736               Family Reunion Planning Kit for Dummies
7864                                   . . .Has Far to Go.
624      Science and Sensibility: The Elegant Logic of ...
12979            Coppola and Eiko on Bram Stoker's Dracula
2060                    Innovation and the General Manager
13897                      Christopher Marlowe: Poet & Spy
5498                           Portraits of the Rainforest
6995                                    Anybody Out There?
9346                       Journey to the End of the Night
7689                                       Death in Berlin
6968        The Devil at Large: Erica Jong on Henry Miller
8607                                               Rejoice
1836     J.R.R. Tolkien's Sanctifying Myth: Understandi...
Name: title, dtype: object

In [52]:
recommend('1984')

INDEX: 4184
BOOK:

,title,author
4188,Animal Farm/1984,"George Orwell,Richard Brown,Ralph Cosham"
7272,Homage to Catalonia,"George Orwell,Lionel Trilling"
7278,"The Orwell Reader: Fiction, Essays, and Reportage","George Orwell,Richard H. Rovere"
9585,Thirteen O’Clock,Thurston Clarke
7267,A Collection of Essays,George Orwell

In [26]:
books[books["title"] == "1984"][["title","author"]]

     title                                             author
4184  1984  George Orwell,Erich Fromm,Regina Silveira,Marc...

In [27]:
books[books["title"] == "1984"]["description"].iloc[0]

"The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever.,is still the great modern classic of \\negative utopia\\—a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny th,The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever.,is still the great modern classic of \\negative utopia\\—a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions—a power that seems to grow, not lessen, with the passage of time."

In [28]:
books.index

RangeIndex(start=0, stop=14987, step=1)

In [29]:
books.head()

,bookId,title,author,genres,description,content
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",The war against Voldemort is not going well; e...,Harry Potter and the Half-Blood Prince J.K. Ro...
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",There is a door at the end of a silent corrido...,Harry Potter and the Order of the Phoenix J.K....
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",Harry Potter's life is miserable. His parents ...,Harry Potter and the Sorcerer's Stone J.K. Row...
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",The Dursleys were so mean and hideous that sum...,Harry Potter and the Chamber of Secrets J.K. R...
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...","For twelve long years, the dread fortress of A...",Harry Potter and the Prisoner of Azkaban J.K. ...

In [30]:
books = books.drop_duplicates(
    subset=["title"]
)

In [31]:
books[
    books["title"].str.contains(
        "Homo",
        case=False,
        na=False
    )
][["title", "description"]]

,title,description
1061,Lysis/Phaedrus/Symposium: Plato on Homosexuality,"\And when the other is beside him, he shares h..."
7548,Homo Faber,Walter Faber is an emotionally detached engine...
7549,Das Frauenbild In Den Romanen Stiller Und Homo...,Das Anliegen dieser Untersuchung besteht wenig...
7550,Homo faber,Max Frischs Homo faber ist eines der wichtigst...
7551,Homo faber: Ein Bericht,Max Frischs Homo faber ist eines der wichtigst...
7552,Homo faber: Ein Bericht.,Max Frischs Homo faber ist eines der wichtigst...
7553,Der Leser Im Dilemma: Die Leserrolle in Max Fr...,Seit die Literaturwissenschaft ihre Aufmerksam...
8291,Eight Ate: A Feast of Homonym Riddles,This collection of original riddles is unlike ...
12664,Spiritual Bloomsbury: Hinduism and Homosexuali...,A Spiritual Bloomsbury is an exploration of ho...
12669,"Sexual Moralities in France, 1780-1980: New Id...",If the 1960s have already become the subject o...
13742,Ecce Homo,"For lovers of timeless classics, this series o..."

In [32]:
books.to_csv(
    "../data/processed/books_for_ml.csv",
    index=False
)

In [33]:
books["content"] = (
    books["title"].fillna("") + " " +
    books["author"].fillna("") + " " +
    books["genres"].fillna("") + " " +
    books["description"].fillna("")
)

In [34]:
books["content"].iloc[0][:500]

"Harry Potter and the Half-Blood Prince J.K. Rowling Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetr"

In [35]:
books.columns.tolist()

['bookId', 'title', 'author', 'genres', 'description', 'content']

In [36]:
print(books["content"].iloc[4768][:500])

Howl's Moving Castle, Vol. 4 Hayao Miyazaki,Diana Wynne Jones Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfic

In [37]:
print(tfidf_matrix.shape)

(14987, 10000)

In [38]:
print(books.shape)

(14987, 6)

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    tfidf_matrix[4768],
    tfidf_matrix
)

similarities.shape

(1, 14987)

In [40]:
print(books.iloc[4768]["title"])

Howl's Moving Castle, Vol. 4

In [54]:
print(books.loc[4768, "title"])

Howl's Moving Castle, Vol. 4

In [ ]:
print(books.loc[4184, "content"][:200])

1984 George Orwell,Erich Fromm,Regina Silveira,Marc... Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Hor

In [42]:
idx = title_to_index["1984"]

print(idx)
print(books.iloc[idx]["title"])

4184
1984

In [43]:
title_to_index = {
    title: idx
    for idx, title in enumerate(books["title"])
}